## Configuration file for starship shell prompt saved in ~/.config/starship.toml. 
## ANSI colour referece table: https://i.stack.imgur.com/KTSQa.png. 	

# Prompt-wide option for confiruing the format of the prompt. Ordering of '$line_break' matters. 
format = """
$username\
$hostname\
$directory\
$sudo\
$line_break\
$character\
$cmd_duration"""

# Prompt-wide option to disable the blank line at the start of the prompt.
add_newline = false

# Separate the prompt into two lines.
[line_break]
disabled = false 

# Show how long the last command took to execute.
[cmd_duration]
disabled = true

# Show a character telling whether the last command was successful or not.
[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✖](bold red) '

# Show the path to your current directory with some or no context.
[directory]
truncation_length = 1
format = '[$path]($style)[$read_only]($read_only_style)'
style = 'bold fg:253'

# Show the system hostname.
[hostname]
ssh_only = false
format = '[@](bold white)[$hostname](bold fg:214)[:](bold white) '
# String that the hostname is cutoff at after the first match. '' will disable truncation.
trim_at = '.' 
disabled = false

# Show the active user's username.
[username]
#style_user = 'cyan bold'
#style_root = 'black bold'
format = '[$user](bold fg:14)'
disabled = false
show_always = true

# Displays if sudo credentials are currently cached.
[sudo]
format = '[ $symbol]($style)'
style = 'bold green'
symbol = '# '
disabled = false
